<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <form method="POST" action="logic/login.php">
        
        <label for="email">Email :</label><br>
        <input type="email" name="email"><br><br>

        <label for="password">Mot de passe :</label><br>
        <input type="password" name="password"><br><br>

        <button type="submit">Se connecter</button>
    </form>
</body>
</html>