<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8" />
    <title>document</title>
</head>
<body>
    <h1>Test mot de passe</h1>
    <form action="decrypt_password.php" method="POST">
        
        <label for="password">Mot de passe en clair :</label><br>
        <input type="password" name="password">

        <label for="hashed_password">Mot de passe chiffré :</label>
        <input type="text" name="hashed_password">

        <button type="submit">Envoyer</button>
    </form>
</body>
</html>
